using System.Text;
using System.Text.Json;
using MyAIStudioBackend.Models;

namespace MyAIStudioBackend.Services
{
    public class GeminiApiService : IGeminiApiService
    {
        private readonly HttpClient _httpClient;
        private readonly IConfiguration _configuration;
        private readonly ILogger<GeminiApiService> _logger;

        public GeminiApiService(HttpClient httpClient, IConfiguration configuration, ILogger<GeminiApiService> logger)
        {
            _httpClient = httpClient;
            _configuration = configuration;
            _logger = logger;
        }

        public async Task<ChatResponseDto> GenerateContentAsync(ChatRequestDto request)
        {
            // Retrieve API key from Environment or appsettings configuration
            var apiKey = Environment.GetEnvironmentVariable("GEMINI_API_KEY") 
                         ?? _configuration["Gemini:ApiKey"];

            if (string.IsNullOrWhiteSpace(apiKey))
            {
                return new ChatResponseDto
                {
                    Error = "Google AI Studio GEMINI_API_KEY is missing. Please set GEMINI_API_KEY in environment variables or appsettings.json."
                };
            }

            var model = string.IsNullOrWhiteSpace(request.Model) 
                ? (_configuration["Gemini:DefaultModel"] ?? "gemini-3.5-flash") 
                : request.Model;

            var url = $"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={apiKey}";

            var payload = new GeminiApiPayload
            {
                Contents = request.Messages.Select(m => new GeminiContent
                {
                    Role = m.Role == "assistant" ? "model" : "user",
                    Parts = new List<GeminiPart> { new GeminiPart { Text = m.Content } }
                }).ToList(),
                SystemInstruction = !string.IsNullOrWhiteSpace(request.SystemPrompt)
                    ? new GeminiSystemInstruction
                    {
                        Parts = new List<GeminiPart> { new GeminiPart { Text = request.SystemPrompt } }
                    }
                    : null,
                GenerationConfig = new GeminiGenerationConfig { Temperature = 0.7 }
            };

            var jsonContent = JsonSerializer.Serialize(payload);
            var httpRequest = new HttpRequestMessage(HttpMethod.Post, url)
            {
                Content = new StringContent(jsonContent, Encoding.UTF8, "application/json")
            };

            httpRequest.Headers.Add("User-Agent", "aistudio-build-csharp");

            try
            {
                var response = await _httpClient.SendAsync(httpRequest);
                var responseBody = await response.Content.ReadAsStringAsync();

                if (!response.IsSuccessStatusCode)
                {
                    _logger.LogError("Gemini API Error Response: {ResponseBody}", responseBody);
                    return new ChatResponseDto
                    {
                        Error = $"Gemini API returned status code {(int)response.StatusCode}: {responseBody}"
                    };
                }

                var geminiResult = JsonSerializer.Deserialize<GeminiApiResponse>(responseBody);

                if (geminiResult?.Error != null && !string.IsNullOrEmpty(geminiResult.Error.Message))
                {
                    return new ChatResponseDto { Error = geminiResult.Error.Message };
                }

                var textResponse = geminiResult?.Candidates?.FirstOrDefault()
                    ?.Content?.Parts?.FirstOrDefault()?.Text;

                return new ChatResponseDto
                {
                    Text = textResponse ?? "No response content generated by Google AI Studio model."
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Exception thrown while calling Gemini API");
                return new ChatResponseDto
                {
                    Error = $"Internal C# Server Exception: {ex.Message}"
                };
            }
        }
    }
}
