import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

// Initialize Gemini client with standard user-agent and API key
const apiKey = process.env.GEMINI_API_KEY;
const ai = apiKey
  ? new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    })
  : null;

app.use(express.json());

// API route for chat proxy (keeps API Key secure)
app.post("/api/chat", async (req, res) => {
  try {
    if (!ai) {
      return res.status(500).json({
        error: "Google AI Studio API Key is not configured on the server. Please add GEMINI_API_KEY in Settings > Secrets.",
      });
    }

    const { messages, systemPrompt, model = "gemini-3.5-flash" } = req.body;

    if (!messages || !Array.isArray(messages)) {
      return res.status(400).json({ error: "Invalid 'messages' format. Must be an array." });
    }

    // Convert messages to Gemini format: { role: 'user' | 'model', parts: [{ text: '...' }] }
    // Note: Gemini uses 'user' and 'model' as roles (not 'assistant')
    const contents = messages.map((m: any) => ({
      role: m.role === "assistant" ? "model" : "user",
      parts: [{ text: m.content }],
    }));

    const response = await ai.models.generateContent({
      model: model,
      contents,
      config: {
        systemInstruction: systemPrompt || "You are a helpful coding assistant inside a Visual Studio extension.",
        temperature: 0.7,
      },
    });

    res.json({
      text: response.text || "No response generated by the model.",
    });
  } catch (error: any) {
    console.error("Gemini API Proxy Error:", error);
    res.status(500).json({
      error: error.message || "An unexpected error occurred while communicating with Google AI Studio.",
    });
  }
});

// Serve Vite files or static content
async function initServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    // SPA routing - Express v4 uses '*'
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`[Server] Running on http://0.0.0.0:${PORT}`);
  });
}

initServer().catch((err) => {
  console.error("Failed to start server:", err);
});
