import { AIChannel } from "../types";

export const AI_CHANNELS: AIChannel[] = [
  {
    id: "aistudio",
    name: "Google AI Studio",
    provider: "Google Cloud / DeepMind",
    category: "Google",
    isFreeTier: true,
    defaultModel: "gemini-3.5-flash",
    availableModels: ["gemini-3.5-flash", "gemini-3.1-pro-preview", "gemini-2.5-flash", "gemini-2.5-pro"],
    description: "Official Google Developer platform powered by Gemini models with large context windows and fast code synthesis.",
    badge: "Recommended • Free Tier",
    badgeColor: "bg-indigo-950 text-indigo-300 border-indigo-800",
    requiresApiKey: false, // Built-in server proxy or custom GEMINI_API_KEY
    docUrl: "https://aistudio.google.com",
    features: ["Server-Side GenAI SDK", "Multimodal Analysis", "1M+ Context Window", "C# & VS Extension Support"]
  },
  {
    id: "base44",
    name: "Base44 AI Engine",
    provider: "Base44 Workspace",
    category: "AI Builder",
    isFreeTier: true,
    defaultModel: "base44-coder-v2",
    availableModels: ["base44-coder-v2", "base44-agent-fast", "base44-omni"],
    description: "Full-stack developer AI workspace channel designed for automatic full-app generation and C# / React integrations.",
    badge: "Free Developer Tier",
    badgeColor: "bg-emerald-950 text-emerald-300 border-emerald-800",
    requiresApiKey: true,
    docUrl: "https://base44.io",
    features: ["Instant Code Generation", "Full-Stack Project Sync", "AST Refactoring", "Free API Tier"]
  },
  {
    id: "replit",
    name: "Replit Agent AI",
    provider: "Replit Inc.",
    category: "AI Builder",
    isFreeTier: true,
    defaultModel: "replit-code-v1.5",
    availableModels: ["replit-code-v1.5", "replit-agent-pro", "replit-ghostwriter"],
    description: "Cloud IDE & Agent integration supporting remote execution, live debugging, and multi-file code editing.",
    badge: "Free Community",
    badgeColor: "bg-amber-950 text-amber-300 border-amber-800",
    requiresApiKey: true,
    docUrl: "https://replit.com",
    features: ["Cloud REPL Sandbox", "Multi-language Support", "Auto-debugging", "Real-time Terminal Output"]
  },
  {
    id: "vercel",
    name: "Vercel AI SDK / v0",
    provider: "Vercel",
    category: "Cloud Platform",
    isFreeTier: true,
    defaultModel: "v0-code-assistant",
    availableModels: ["v0-code-assistant", "vercel-ai-sdk-v4", "claude-3.5-sonnet-via-vercel"],
    description: "Vercel's unified AI SDK bridge & v0 generative component engine for high-speed UI and API code generation.",
    badge: "Free Hobby Tier",
    badgeColor: "bg-slate-900 text-gray-200 border-gray-700",
    requiresApiKey: true,
    docUrl: "https://vercel.com/ai",
    features: ["Vercel AI SDK Integration", "Edge Proxy Streaming", "React & Component Logic", "Hobby Gateway"]
  },
  {
    id: "lovable",
    name: "Lovable AI",
    provider: "Lovable Devs",
    category: "AI Builder",
    isFreeTier: true,
    defaultModel: "lovable-engineer-v1",
    availableModels: ["lovable-engineer-v1", "lovable-swift-code"],
    description: "Generative UI and full-stack software development engine tuned for responsive layouts and clean C#/TS code.",
    badge: "Free Creator Tier",
    badgeColor: "bg-rose-950 text-rose-300 border-rose-800",
    requiresApiKey: true,
    docUrl: "https://lovable.dev",
    features: ["Visual-to-Code Synthesis", "Clean Component Architecture", "Free Monthly Credits", "IDE Extension Plugin"]
  },
  {
    id: "groq",
    name: "Groq Llama 3 (Ultra-Fast)",
    provider: "Groq Cloud LPU",
    category: "Free API Provider",
    isFreeTier: true,
    defaultModel: "llama-3.3-70b-versatile",
    availableModels: ["llama-3.3-70b-versatile", "llama-3.1-8b-instant", "mixtral-8x7b-32768", "deepseek-r1-distill-llama-70b"],
    description: "Ultra-high speed LPU inference API providing up to 800 tokens/sec. 100% free daily rate limits for developers.",
    badge: "100% Free API • 800 tok/s",
    badgeColor: "bg-orange-950 text-orange-300 border-orange-800",
    requiresApiKey: true,
    docUrl: "https://console.groq.com",
    features: ["Instant Response Speed", "Llama 3.3 70B & DeepSeek R1", "OpenAI Compatible API", "1440 Requests / Day Free"]
  },
  {
    id: "openrouter",
    name: "OpenRouter (Free Hub)",
    provider: "OpenRouter",
    category: "Free API Provider",
    isFreeTier: true,
    defaultModel: "deepseek/deepseek-r1:free",
    availableModels: ["deepseek/deepseek-r1:free", "google/gemini-2.5-flash:free", "qwen/qwen-2.5-coder-32b:free", "meta-llama/llama-3.3-70b:free"],
    description: "Unified router providing access to dozens of top open-weights models with unlimited free model endpoints.",
    badge: "Dozens of Free Models",
    badgeColor: "bg-cyan-950 text-cyan-300 border-cyan-800",
    requiresApiKey: true,
    docUrl: "https://openrouter.ai",
    features: ["DeepSeek R1 Free", "Qwen Coder 32B", "Unified Endpoint", "Zero Rate Limit Fallbacks"]
  },
  {
    id: "huggingface",
    name: "Hugging Face Inference API",
    provider: "Hugging Face",
    category: "Free API Provider",
    isFreeTier: true,
    defaultModel: "Qwen/Qwen2.5-Coder-32B-Instruct",
    availableModels: ["Qwen/Qwen2.5-Coder-32B-Instruct", "meta-llama/Llama-3.2-3B-Instruct", "mistralai/Mistral-7B-Instruct-v0.3"],
    description: "Open community hub powering serverless inference for thousands of fine-tuned open source coding models.",
    badge: "Serverless Free Tier",
    badgeColor: "bg-yellow-950 text-yellow-300 border-yellow-800",
    requiresApiKey: true,
    docUrl: "https://huggingface.co",
    features: ["Free Community API Key", "Fine-tuned Code LLMs", "Open Weights Hub", "Custom Model Uploads"]
  },
  {
    id: "together",
    name: "Together AI",
    provider: "Together.ai",
    category: "Free API Provider",
    isFreeTier: true,
    defaultModel: "togethercomputer/CodeLlama-34b-Instruct",
    availableModels: ["togethercomputer/CodeLlama-34b-Instruct", "mistralai/Mixtral-8x7b-Instruct", "Qwen/Qwen2.5-Coder-32B"],
    description: "Fast cloud inference platform for open-source AI models with starter developer credits.",
    badge: "Free Starter Credits",
    badgeColor: "bg-purple-950 text-purple-300 border-purple-800",
    requiresApiKey: true,
    docUrl: "https://together.ai",
    features: ["Fast Streaming API", "CodeLlama & Mixtral", "Sub-second Latency", "Starter Credits"]
  },
  {
    id: "mistral",
    name: "Mistral AI (Codestral)",
    provider: "Mistral AI",
    category: "Free API Provider",
    isFreeTier: true,
    defaultModel: "codestral-latest",
    availableModels: ["codestral-latest", "mistral-large-latest", "mistral-small-latest"],
    description: "Dedicated coding model platform featuring Codestral, specifically optimized for 80+ programming languages including C# and C++.",
    badge: "Codestral Free Tier",
    badgeColor: "bg-red-950 text-red-300 border-red-800",
    requiresApiKey: true,
    docUrl: "https://mistral.ai",
    features: ["Codestral 80+ Languages", "Fill-in-the-Middle (FIM)", "Fast Code Completion", "Developer Tier"]
  },
  {
    id: "ollama",
    name: "Ollama / Local AI",
    provider: "Self-Hosted / Localhost",
    category: "Local / Open Source",
    isFreeTier: true,
    defaultModel: "codellama:13b",
    availableModels: ["codellama:13b", "qwen2.5-coder:7b", "deepseek-coder:6.7b", "llama3.2:3b"],
    description: "Run models completely offline and privately on your local PC or workstation using Ollama on port 11434.",
    badge: "100% Offline • Local Privacy",
    badgeColor: "bg-teal-950 text-teal-300 border-teal-800",
    requiresApiKey: false,
    endpointUrl: "http://localhost:11434",
    docUrl: "https://ollama.com",
    features: ["Zero Data Exposure", "Offline Execution", "No API Keys Needed", "Unlimited Usage"]
  }
];

export function getChannelById(id: string): AIChannel {
  return AI_CHANNELS.find((c) => c.id === id) || AI_CHANNELS[0];
}
